<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Customer\Block\Adminhtml\Edit\Tab\View\PersonalInfo
 */

$lastLoginDateAdmin = $block->getLastLoginDate();
$lastLoginDateStore = $block->getStoreLastLoginDate();

$createDateAdmin = $block->getCreateDate();
$createDateStore = $block->getStoreCreateDate();

?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Last Logged In:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $lastLoginDateAdmin ?> (<?php /* @escapeNotVerified */ echo $block->getCurrentStatus() ?>)</td>
        </tr>
        <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Last Logged In (%1):', $block->getStoreLastLoginDateTimezone()) ?></th>
            <td><?php /* @escapeNotVerified */ echo $lastLoginDateStore ?> (<?php /* @escapeNotVerified */ echo $block->getCurrentStatus() ?>)</td>
        </tr>
        <?php endif; ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Account Lock:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getAccountLock() ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Confirmed email:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getIsConfirmedStatus() ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Account Created:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $createDateAdmin ?></td>
        </tr>
        <?php if ($createDateAdmin != $createDateStore): ?>
            <tr>
                <th><?php /* @escapeNotVerified */ echo __('Account Created on (%1):', $block->getStoreCreateDateTimezone()) ?></th>
                <td><?php /* @escapeNotVerified */ echo $createDateStore ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Account Created in:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getCreatedInStore() ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */ echo __('Customer Group:') ?></th>
            <td><?php /* @escapeNotVerified */ echo $block->getGroupName() ?></td>
        </tr>
        </tbody>
    </table>
    <address>
        <strong><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></strong><br/>
        <?php echo $block->getBillingAddressHtml() ?>
    </address>

</div>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();

if(strpos($store->getCurrentUrl() , 'delivery_price_target') == true){?>
<script>

    require([ 'jquery', 'jquery/ui'], function($){

        $(document).ready(function(){
            $("#tab_block_customer_edit_tab_delivery").trigger('click');
        });

    });
</script>
<?php  } elseif(strpos($store->getCurrentUrl() , 'localtion_save_target') == true){?>
    <script>

        require([ 'jquery', 'jquery/ui'], function($){

            $(document).ready(function(){
                $("#tab_block_customer_edit_tab_locations").trigger('click');
            });

        });
    </script>
<?php
}
 elseif(strpos($store->getCurrentUrl() , 'manage_free_delivery_save_target') == true){?>

     <script>

         require([ 'jquery', 'jquery/ui'], function($){

             $(document).ready(function(){
                 $("#manage-free-delivery").trigger('click');
                 $("#tab_block_customer_edit_tab_delivery").trigger('click');

             });

         });
     </script>
<?php  } ?>
