<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
// updated file to add notification for seller.
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner = $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$allow_pro_type = $_helper->getAllowedProductType();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
$productNotificationCount = $block->getProductNotificationCount();
$orderNotificationCount = $block->getOrderNotificationCount();
$transactionCount = $block->getTransactionNotificationCount();
$_deliveryhelper = $this->helper('Bakeway\Deliveryrangeprice\Helper\Data');

?>

<style type="text/css">
    @media only screen and (max-width: 767px) {

        .block-collapsible-nav.wk-mp-main {
            top: 20px;
        }
    }

    .block-collapsible-nav .item .notifications-action a:before, .block-collapsible-nav .nav a:before {
        content: none
    }

    .notification-link .notification-block {
        position: absolute;
        top: -2px;
        left: 188px !important;
    }

    @media only screen and (max-width: 736px) and (min-width: 320px) {
        .notification-block .notification-count{left:0%}
    }

</style>
<div class="seller-dashborad-sidebar">
    <div class="block account-nav block-collapsible-nav wk-mp-main">
        <div class="title block-collapsible-nav-title"
             data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-seller", "selectorsToggleClass": "active"}}'>
            <strong><?php /* @escapeNotVerified */
                echo __('Marketplace'); ?></strong>
        </div>
        <div class="content block-collapsible-nav-content" id="block-collapsible-nav-seller">
            <nav class="account-nav">
                <ul class="nav items">
                    <?php
                    if ($isPartner) { ?>
                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/account/dashboard')) || !$isSellerGroup) { ?>
                            <li class="nav item <?php echo strpos($magentoCurrentUrl, 'partner/account/dashboard') ? "current" : ""; ?>">
                                <?php
                                if (strpos($magentoCurrentUrl, 'partner/account/dashboard') !== false) { ?>
                                    <strong><?php echo __('Dashboard') ?></strong>
                                    <?php
                                } else { ?>
                                    <a href="<?php echo $block->getUrl('partner/account/dashboard', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Dashboard') ?>
                                    </a>
                                    <?php
                                } ?>
                            </li>
                            <?php
                        } ?>    
                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/order/history')) || !$isSellerGroup) { ?>
                            <li class="nav item notification-link  <?php echo strpos($magentoCurrentUrl, 'partner/order') && (!strpos($magentoCurrentUrl, 'partner/order/shipping/')) ? "current" : ""; ?>">
                                <?php
                                if (strpos($magentoCurrentUrl, 'partner/order') !== false && strpos($magentoCurrentUrl, 'partner/order/shipping/') === false) { ?>
                                    <strong><?php echo __('Order') ?></strong>
                                    <?php
                                } else { ?>
                                    <a href="<?php echo $block->getUrl('partner/order/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Order') ?>
                                    </a>
                                    <?php if ($block->getMarketplaceOrderCollection()->getSize()) { ?>

                                        <div class="notification-block">
                                            <a href="" class="notifications-action partner-dropdown">
                                                <img height="20" width="20"
                                                     src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>"
                                                     class="notifications-img"/>
                                                <?php if ($orderNotificationCount > 5): ?>
                                                    <span class="notification-count">5+</span>
                                                <?php else: ?>
                                                    <span class="notification-count"><?php echo $orderNotificationCount; ?></span>
                                                <?php endif; ?>
                                            </a>
                                            <?php /*<ul class="partner-dropdown-menu">
                                                <span class="notify-point"></span>
                                                <?php
                                                $orderDisplayCount = 1;
                                                foreach ($block->getMarketplaceOrderCollection() as $order):
                                                    if ($orderDisplayCount <= 5):
                                                        ?>
                                                        <li class="notifications-entry">
                                                            <strong class="notifications-entry-title">
                                                                <?php echo $block->getOrderNotificationTitle($order->getOrderId()); ?>
                                                            </strong>
                                                            <p class="notifications-entry-description _cutted">
                                                                <a href="<?php echo $block->getUrl('partner/order/view', ['id' => $order->getOrderId(), 'n' => 1, '_secure' => $this->getRequest()->isSecure()]) ?>"
                                                                   class="notifications-entry-description-start">
                                                    <span>
                                                        <?php echo $block->getOrderNotificationDesc($order->getOrderId()); ?>
                                                    </span>
                                                                </a>
                                                            </p>
                                                            <time class="notifications-entry-time">
                                                                <?php echo $block->getOrderCreatedDate($order->getOrderId()); ?>
                                                            </time>
                                                        </li>
                                                        <?php
                                                        $orderDisplayCount++;
                                                    endif;
                                                endforeach; ?>
                                                <?php
                                                if ($orderDisplayCount > 5):
                                                    ?>
                                                    <li class="notifications-entry notifications-entry-last">
                                                        <a href="<?php echo $block->getUrl('partner/order/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                            <?php echo __('Click here to view order history'); ?>
                                                        </a>
                                                    </li>
                                                <?php endif; ?>
                                            </ul> */?>
                                        </div>
                                    <?php } ?>
                                    <!-- Orders Notification End -->
                                    <?php
                                } ?>
                            </li>
                        <?php } ?>
                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/transaction/history')) || !$isSellerGroup) { ?>
                            <li class="nav item notification-link <?php echo strpos($magentoCurrentUrl, 'partner/transaction/history') ? "current" : ""; ?>">
                                <?php
                                if (strpos($magentoCurrentUrl, 'partner/transaction/history') !== false) { ?>
                                    <strong><?php echo __('Payouts  - Transaction list') ?></strong>
                                    <?php
                                } else { ?>
                                    <a href="<?php echo $block->getUrl('partner/transaction/history', ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo __('Payouts  - Transaction list') ?></a>
                                    <!-- Transaction Notification -->
                                    <?php if ($block->getTransactionCollection()->getSize()) { ?>
                                        <div class="notification-block">
                                            <a href="" class="notifications-action partner-dropdown">
                                                <img height="20" width="20"
                                                     src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>"
                                                     class="notifications-img"/>
                                                <?php if ($transactionCount > 5): ?>
                                                    <span class="notification-count">5+</span>
                                                <?php else: ?>
                                                    <span class="notification-count"><?php echo $transactionCount; ?></span>
                                                <?php endif; ?>
                                            </a>
                                            <ul class="partner-dropdown-menu">
                                                <span class="notify-point"></span>
                                                <?php
                                                $trnDisplayCount = 1;
                                                foreach ($block->getTransactionCollection() as $transaction):
                                                    if ($trnDisplayCount <= 5):
                                                        ?>
                                                  <!--      <li class="notifications-entry">
                                                            <strong class="notifications-entry-title">
                                                                <?php /*echo $block->getTransactionNotifyTitle($transaction->getEntityId()); */?>
                                                            </strong>
                                                            <p class="notifications-entry-description _cutted">
                                                                <a href="<?php /*echo $block->getUrl('partner/transaction/view', ['id' => $transaction->getId(), 'n' => 1, '_secure' => $this->getRequest()->isSecure()]) */?>"
                                                                   class="notifications-entry-description-start">
                                                    <span>
                                                        <?php /*echo $block->getTransactionNotifyDesc($transaction->getEntityId()); */?>
                                                    </span>
                                                                </a>
                                                            </p>
                                                            <time class="notifications-entry-time">
                                                                <?php /*echo $block->getTransactionDate($transaction->getUpdatedAt()); */?>
                                                            </time>
                                                        </li>-->
                                                        <?php $trnDisplayCount++;
                                                    endif;
                                                endforeach; ?>

                                                <?php
                                                if ($trnDisplayCount > 5):
                                                    ?>
                                                    <li class="notifications-entry notifications-entry-last">
                                                        <a href="<?php echo $block->getUrl('partner/transaction/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                            <?php echo __('Click here to view transaction history'); ?>
                                                        </a>
                                                    </li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                    <!-- Transaction Notification End -->
                                    <?php
                                } ?>
                            </li>
                        <?php } ?>

                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/product/productlist')) || !$isSellerGroup) { ?>
                            <li class="nav item notification-link <?php echo strpos($magentoCurrentUrl, 'partner/product/productlist') ? "current" : ""; ?>">
                                <?php if (strpos($magentoCurrentUrl, 'partner/product/productlist') !== false) { ?>
                                    <strong><?php echo __('Products List') ?></strong>
                                <?php } else { ?>
                                    <a href="<?php echo $block->getUrl('partner/product/productlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Products List') ?>
                                    </a>
                                    <!-- Product Notification -->
                                    <?php if ($block->getProductCollection()->getSize()) { ?>
                                        <div class="notification-block">
                                            <a href="" class="notifications-action partner-dropdown">
                                                <img height="20" width="20"
                                                     src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>"
                                                     class="notifications-img"/>
                                                <?php if ($productNotificationCount > 5): ?>
                                                    <span class="notification-count">5+</span>
                                                <?php else: ?>
                                                    <span class="notification-count"><?php echo $productNotificationCount; ?></span>
                                                <?php endif; ?>
                                            </a>
                                            <ul class="partner-dropdown-menu">
                                                <span class="notify-point"></span>
                                                <?php
                                                $productDisplayCount = 1;
                                                foreach ($block->getProductCollection() as $product):
                                                    if ($productDisplayCount <= 5):
                                                        ?>
                                                        <li class="notifications-entry">
                                                            <strong class="notifications-entry-title">
                                                                <?php echo $block->getProductNotificationTitle($product->getMageproductId(), $product->getStatus()); ?>
                                                            </strong>
                                                            <p class="notifications-entry-description _cutted">
                                                                <a href="<?php echo $block->getUrl('partner/product/productlist', ['_secure' => $this->getRequest()->isSecure()]) ?>"
                                                                   class="notifications-entry-description-start">
                                                <span>
                                                    <?php echo $block->getProductNotificationDesc($product->getMageproductId(), $product->getStatus()); ?>

                                                </span>
                                                                </a>
                                                            </p>
                                                            <time class="notifications-entry-time">
                                                                <?php echo $block->getProductNotifyDateTime($product->getUpdatedAt()); ?>
                                                            </time>
                                                        </li>
                                                        <?php $productDisplayCount++;
                                                    endif;
                                                endforeach; ?>
                                                <?php
                                                if ($productDisplayCount > 5):
                                                    ?>
                                                    <li class="notifications-entry notifications-entry-last">
                                                        <a href="<?php echo $block->getUrl('partner/product/productlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                            <?php echo __('Click here to view product list'); ?>
                                                        </a>
                                                    </li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                    <!-- Product Notification End -->
                                <?php } ?>
                            </li>
                        <?php } ?>
                        <li class="nav item <?php echo strpos($magentoCurrentUrl, 'deliveryrangeprice/delivery/rangeprice/') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'deliveryrangeprice/delivery/rangeprice') !== false) { ?>
                                <strong><?php echo __('Manage Delivery & Price') ?></strong>
                                <?php
                            } else { ?>
                                <a href="<?php echo $block->getUrl('deliveryrangeprice/delivery/rangeprice', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Manage Delivery & Price') ?></a>
                                <?php
                            } ?>
                        </li>

                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/product/add')) || !$isSellerGroup) { ?>
                            <li class="nav item <?php echo (strpos($magentoCurrentUrl, 'partner/product/add') || strpos($magentoCurrentUrl, 'partner/product/create')) ? "current" : ""; ?>">
                                <?php
                                if (strpos($magentoCurrentUrl, 'partner/product/add') !== false || strpos($magentoCurrentUrl, 'partner/product/create') !== false) { ?>
                                    <strong><?php echo __('Add New Products') ?></strong>
                                    <?php
                                } else { ?>
                                    <a href="<?php echo $block->getUrl('partner/product/create', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Add New Products') ?>
                                    </a>
                                    <?php
                                } ?>
                            </li>
                        <?php } ?>
                        <!--<li class="nav item <?php echo strpos($magentoCurrentUrl, 'review/customer/') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'review/customer/') !== false) { ?>
                                <strong><?php echo __('Product Reviews') ?></strong>
                                <?php
                            } else { ?>
                                <a href="<?php echo $block->getUrl('review/customer/', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Product Reviews') ?></a>
                                <?php
                            } ?>
                        </li>-->

                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/account/editprofile')) || !$isSellerGroup) { ?>
                            <?php if ($_helper->getSellerProfileDisplayFlag()) { ?>
                                <li class="nav item <?php echo strpos($magentoCurrentUrl, 'partner/account/editprofile') ? "current" : ""; ?>">
                                    <?php if (strpos($magentoCurrentUrl, 'partner/account/editprofile') !== false) { ?>
                                        <strong><?php echo __('My Profile') ?></strong>
                                        <?php
                                    } else { ?>
                                        <a href="<?php echo $block->getUrl('partner/account/editprofile', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                            <?php echo __('My Profile') ?>
                                        </a>
                                        <?php
                                    } ?>
                                </li>
                            <?php } ?>
                        <?php } ?>

                        <li class="nav item <?php echo strpos($magentoCurrentUrl, 'commissionlog/commission/view/') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'commissionlog/commission/view') !== false) { ?>
                                <strong><?php echo __('Commission') ?></strong>
                                <?php
                            } else { ?>
                                <a href="<?php echo $block->getUrl('commissionlog/commission/view', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Commission') ?></a>
                                <?php
                            } ?>
                        </li>
                        <li class="nav item <?php echo strpos($magentoCurrentUrl, 'customer/account/edit/changepass') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'customer/account/edit/changepass') !== false) { ?>
                                <strong><?php echo __('Change Password') ?></strong>
                                <?php
                            } else { ?>
                                  <a href="<?php /* @escapeNotVerified */
                echo $_deliveryhelper ->getPasswordurl() ?>" class="action change-password">
                    <?php /* @escapeNotVerified */
                    echo __('Change Password') ?>
                </a>
                                <?php
                            } ?>
                        </li>
                        <li class="nav item <?php echo strpos($magentoCurrentUrl, 'shopavailability/availability/index') ||    strpos($magentoCurrentUrl, 'shopavailability/availability') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'shopavailability/availability/index') !== false || strpos($magentoCurrentUrl, 'shopavailability/availability') !== false) { ?>
                                <strong><?php echo __('Shop Availability') ?></strong>
                                <?php
                            } else { ?>
                                  <a href="<?php echo $block->getUrl('shopavailability/availability/index', ['_secure' => $this->getRequest()->isSecure()]); ?>" class="action change-password">
                    <?php /* @escapeNotVerified */
                    echo __('Shop Availability') ?>
                </a>
                                <?php
                            } ?>
                        </li>


                        <?php /*if(($isSellerGroup && $_helper->isAllowedAction('partner/product_attribute/new')) || !$isSellerGroup) {
                        if(strpos($allow_pro_type,'configurable') !== false){ ?>
                            <li class="nav item <?php echo strpos($magentoCurrentUrl,'partner/product_attribute/new')? "current":"";?>">
                            <?php if(strpos($magentoCurrentUrl,'partner/product_attribute/new') !== false){ ?>
                                <strong><?php echo __('Create Attribute') ?></strong>
                                <?php }
                                else{ ?>
                                    <a href="<?php echo $block->getUrl('partner/product_attribute/new', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Create Attribute') ?></a>
                                <?php } ?>
                            </li>
                            <?php
                        }
                    } */
                        ?>


                        <?php if (($isSellerGroup && $_helper->isAllowedAction('partner/order/shipping')) || !$isSellerGroup) { ?>
                            <?php if ($_helper->getIsOrderManage() == "1") { ?>
                                <?php /* <li class="nav item <?php echo strpos($magentoCurrentUrl,'partner/order/shipping/')? "current":"";?>">
                            <?php if(strpos($magentoCurrentUrl,'partner/order/shipping') !== false){ ?>
                                <strong><?php echo __('Manage Print PDF Header Info') ?></strong>
                            <?php
                            } else{ ?>
                                <a href="<?php echo $block->getUrl('partner/order/shipping', ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo __('Manage Print PDF Header Info') ?></a>
                            <?php
                            } ?>
                        </li> <?php */ ?>
                                <?php
                            } ?>
                        <?php } ?>
                        <?php echo $block->getChildHtml(); ?>


                        <div id="partner-notification-component" data-bind="scope:'notification-content'">
                            <script type="text/x-magento-init">
                        {
                            "#partner-notification-component": {
                                "Magento_Ui/js/core/app":  <?php /* @escapeNotVerified */
                                echo $block->getJsLayout(); ?>
                            }
                        }


                            </script>
                            <?php echo $block->getChildHtml('reply_template'); ?>
                        </div>
                        <?php
                    } else { ?>
                        <?php echo $block->getChildHtml(); ?>
                        <!-- <li class="nav item <?php echo strpos($magentoCurrentUrl, 'partner/account/becomepartner') ? "current" : ""; ?>">
                            <?php if (strpos($magentoCurrentUrl, 'partner/account/becomeseller') !== false) { ?>
                                <strong><?php echo __('Become Seller') ?></strong>
                            <?php } else { ?>
                                <a href="<?php echo $block->getUrl('partner/account/becomeseller', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Become Seller') ?>
                                </a>
                            <?php } ?>
                        </li>-->
                        <?php
                    } ?>
                </ul>
            </nav>
        </div>
    </div>
</div>