<script type="text/javascript">
    require([
        "jquery",
        "jquery/ui"
    ], function ($) {
        /**suburb list**/
        jQuery("#page_city_id").change(function () {

            var city_id = document.getElementById('page_city_id').value;
            new Ajax.Request('<?php echo $this->getUrl('partnerlocations/locations/suburblist',
        ['_secure' => true]);
?>', {
                method: 'post',
                dataType: "json",
                parameters: {
                    city_id: city_id,
                },
                onSuccess: function (transport) {
                    if (transport.responseJSON.length == 0) {
                        jQuery(".field-sub_loc_id").hide();
                    } else {
                        jQuery(".field-sub_loc_id").show();
                        var suburbHtml = '<select id="page_sub_loc_id" name="page_sub_loc_id" title="Suburb" class=" select admin__control-select required-entry"><option value="">---Please Select---</option>' + transport.responseJSON + '</select>';
                        jQuery('#page_sub_loc_id').replaceWith(suburbHtml);
                    }
                }
            });

        })

    });
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYjq3gU-YfuRTGl2Jzvx8aja3vAIAzsx8&callback=initMap" type="text/javascript"></script>
<button id="myBtn" style="width: 220px;left: 645px;position: relative;top: -75px;">Open Map To Select Lat/Lon</button>
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <form>
            <fieldset class="gllpLatlonPicker" style="border:none;">
                <input type="text" class="gllpSearchField">
                <input type="button" class="gllpSearchButton" value="search">
                <div class="gllpMap" style="width: 500px; height: 250px;">Google Maps</div>
                <input type="hidden" class="gllpLatitude" value="20"/>
                <input type="hidden" class="gllpLongitude" value="20"/>
                <input type="hidden" class="gllpZoom" value="3"/>
                <input type="button" class="gllpUpdateButton" value="update map" style="display:none;">
                <input type="button" class="setLatLon" value="Set Lat/Lon">
            </fieldset>
        </form>
    </div>
</div>