<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Transaction\View */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$payoutHelper = $this->helper('Bakeway\PayoutsCalculation\Helper\Data');
$collection = $block->sellertransactionDetails();
$orderslist = $block->sellertransactionOrderDetails($this->getRequest()->getParam('id'));
?>
<div class="wk-mp-design">
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend"><span><?php echo __('Transaction Id %1 - %2', $collection->getTransactionId(), __('Paid')) ?></span></legend>
		<div class="wk-mp-order-info-box">
			<div>
				<div class="box">
					<div class="box-title">
						<h2><?php echo __('Transaction Information') ?></h2>
					</div>
					<div class="box-content">
						<div class="wk_row">
							<span class="label"><?php echo __('Date')?> : </span>
							<span class="value"><?php echo $block->formatDate($collection->getCreatedAt(), \IntlDateFormatter::LONG); ?></span>
						</div>
						<div class="wk_row">
							<span class="label"><?php echo __('Amount')?> : </span>
							<span class="value"><?php echo $helper->getFormatedPrice($collection->getTransactionAmount()); ?></span>
						</div>
						<div class="wk_row">
							<span class="label"><?php echo __('Type')?> : </span>
							<span class="value"><?php echo $collection->getType(); ?></span>
						</div>
						<div class="wk_row">
							<span class="label"><?php echo __('Method')?> : </span>
							<span class="value"><?php echo $collection->getMethod(); ?></span>
						</div>
						<div class="wk_row">
							<?php
							if($collection->getCustomNote()){
								$customnote = $collection->getCustomNote();
							}else{
								$customnote = __('None');
							}
							?>
							<span class="label"><?php echo __('Comment Message')?> : </span>
							<span class="value"><?php echo $customnote; ?></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="order-details-items ordered">
			<div class="table-wrapper order-items">
				<h2 class="table-caption"><?php echo __('Transaction Order Information') ?></h2>
				<table class="data table table-order-items" summary="<?php echo __('Order List Per Product') ?>">
					<thead>
					<tr>
						<th class="col price"><?php echo __('Order #') ?></th>
						<th class="col price"><?php echo __('Product Name') ?></th>
						<th class="col price"><?php echo __('Price') ?></th>
						<th class="col price"><?php echo __('Qty') ?></th>
						<th class="col price"><?php echo __('Total Price') ?></th>
						<th class="col price"><?php echo __('Total Tax') ?></th>
						<th class="col price"><?php echo __('Delivery Charge') ?></th>
						<th class="col price"><?php echo __('TCS Amount') ?></th>
						<th class="col price"><?php echo __('PG Fee') ?></th>
						<th class="col price"><?php echo __('Commission Incl Tax') ?></th>
						<th class="col price"><?php echo __('Subtotal') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php $i = 0; ?>
					<?php $_count = count($orderslist); ?>
					<?php
					$subtotal = 0;
					foreach($orderslist as $item){
						$i++;
						$mageorderid = $item->getOrderId();
						$item_status="";
						$subtotal=$subtotal+$item->getActualSellerAmount();

						/**
						 * Bakeway Fields
						 */
						$tcsFee = 0;
						$pgFee = 0;
						$deliveryCharge = 0;
						$payoutsAmount = 0;
						if($item->getIsShipping()) {
							$tcsFee = $payoutHelper->getTcsByOrderId($mageorderid);
							$pgFee = $payoutHelper->getPgFeeByOrderId($mageorderid);
							$deliveryCharge = $payoutHelper->getDeliveryChargeByOrderId($mageorderid);
						}
						$payoutsAmount = $payoutsAmount + $deliveryCharge - $tcsFee - $pgFee;
						?>
						<tr class="border">
							<td class="col price" data-th="<?php echo __('Order #') ?>"><?php echo $item->getMagerealorderId();?></td>
							<td class="col price" data-th=="<?php echo __('Product Name') ?>"><?php echo $item['magepro_name'];?></td>
							<td class="col price" data-th=="<?php echo __('Price') ?>"><?php echo $helper->getFormatedPrice($item->getMageproPrice());?></td>
							<td class="col price" data-th=="<?php echo __('Qty') ?>"><?php echo $item->getMagequantity();?></td>
							<td class="col price" data-th=="<?php echo __('Total Price') ?>"><?php echo $helper->getFormatedPrice($item->getTotalAmount());?></td>
							<td class="col price" data-th=="<?php echo __('Total Tax') ?>"><?php echo $helper->getFormatedPrice($item->getTotalTax());?></td>
							<td class="col price" data-th=="<?php echo __('Delivery Charge') ?>"><?php echo $helper->getFormatedPrice($deliveryCharge);?></td>
							<td class="col price" data-th=="<?php echo __('TCS Amount') ?>"><?php echo $helper->getFormatedPrice($tcsFee);?></td>
							<td class="col price" data-th=="<?php echo __('PG Fee') ?>"><?php echo $helper->getFormatedPrice($pgFee);?></td>
							<td class="col price" data-th=="<?php echo __('Admin Commission') ?>"><?php echo $helper->getFormatedPrice($item->getCommissionInclTax());?></td>
							<!--<td class="col price" data-th=="<?php echo __('Admin Commission') ?>"><?php echo $helper->getFormatedPrice($item->getTotalCommission());?></td>-->
							<?php
							$admintotaltax = 0;
							$vendortotaltax = 0;
							if(!$helper->getConfigTaxManage()){
								$admintotaltax = $item->getTotalTax();
							}else{
								$vendortotaltax = $item->getTotalTax();
							}
							?>
							<td class="col price" data-th="<?php echo __('Subtotal') ?>"><?php echo $helper->getFormatedPrice($item->getActualSellerAmount()+$vendortotaltax+$payoutsAmount);?></td>
						</tr>
						<?php
					} ?>
					</tbody>
				</table>
			</div>
		</div>
	</fieldset>
</div>
<div class="buttons-set">
	<p class="back-link">
		<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
	</p>
</div>