<style>
    #wrapper #data_table tr {
        border-bottom: 1px solid #ccc;
    }

    .button.delete {
        float: left;
        margin-left: 8px;
    }

    .button.edit, .button.editsave {
        float: left;
        margin-right: 5%;
    }

    #data_table tr td {
        width: 14%;
    }

    #data_table .save {
        margin-right: 3%;
    }

    #data_table_default .delivery {
        margin-left: 45px;
    }

    #data_table_default select {
        width: 15%;
        margin-left: 7px;
    }

    #delivery-range-main-div {
    }

    #delivery-range-main-div ul li {
        list-style: none;
    }

    #wrapper {
        margin-top: 32px;
    }

    .deliveryoption {
        padding-left: 22px
    }


    .active-delivery-button {
        color: #fff  !important; background-color: #eb5202 !important;border-color: #eb5202;
    }

    .free-shipping-div{margin-top:30px; border-top:2px solid #ddd; padding-top: 10px}
    .free-ship-title{font-weight: bold; font-size: 17px;}
    .free-ship-title h5 {margin-bottom:0px }
    .onoffswitch {
        position: relative; width: 90px;
        -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;
        margin:7px 0px 28px 0px;
    }
    .onoffswitch-checkbox {
        display: none;
    }
    .onoffswitch-label {
        display: block; overflow: hidden; cursor: pointer;
        border: 2px solid #999999; border-radius: 20px;
    }
    .onoffswitch-inner {
        display: block; width: 200%; margin-left: -100%; transition: margin 0.3s ease-in 0s;
    }
    .onoffswitch-inner:before, .onoffswitch-inner:after {  display: block; float: left; width: 50%; height: 30px; padding: 0; line-height: 30px;  font-size: 14px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;  box-sizing: border-box;
    }
    .onoffswitch-inner:before {
        content: "ON"; padding-left: 10px;background-color: #34A7C1; color: #FFFFFF;
    }
    .onoffswitch-inner:after {
        content: "OFF";padding-right: 10px; background-color: #EEEEEE; color: #999999; text-align: right;
    }
    .onoffswitch-switch {
        display: block; width: 18px; margin: 6px; background: #FFFFFF; position: absolute; top: 0; bottom: 0; right: 56px;  border: 2px solid #999999; border-radius: 20px;transition: all 0.3s ease-in 0s;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {  margin-left: 0;
    }
    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {  right: 0px;
    }
    .free-shipping-div .data-grid tbody tr:td{color: green;font-weight: bold;  font-size: 18px;}

</style>
<?php $_DeliveryValue = $block->getDeliveryvalue($block->getCustomerId()); ?>
<?php $grabValue  = $block->getGrabvalue($block->getCustomerId()); ?>

<?php
$deliveryRangepricehelper = $this->helper('Bakeway\Deliveryrangeprice\Helper\Data');
$grabhelper = $this->helper('Bakeway\GrabIntigration\Helper\Data');
$grabSellerFlag = false;
/**
 * grab status set enable when its enable for single store
 */
$grabCount =  $grabhelper->getGrabForSellerforAnySingleStore($block->getCustomerId());
if($grabCount > 0){
    $grabSellerFlag = true;
}
?>


<?php $logsHelper = $this->helper('Bakeway\Logs\Helper\Data');?>
<div id="delivery-loader" style="display: none;"><img
            src="<?php echo $block->getViewFileUrl('Bakeway_Deliveryrangeprice::images/ajaxloder.gif'); ?>"></div>
<input type="hidden" name="seller_id" id="seller_id" value="<?php echo $block->getCustomerId(); ?>"/>
<input type="hidden" name="seller_email" id="seller_email"
       value="<?php echo $block->getSellerEmail($block->getCustomerId()); ?>"/>
<input type="hidden" name="updated_time" id="updated_time" value="<?php echo date("Y-m-d  h:i:s"); ?>"/>

<button type="submit" title="Save" id="manage-delivery" class="button add active-delivery-button" value="Add Row">
    <span><span><span>Manage Delivery & Price</span></span></span>
</button>

<!--hide manage free delivery option when seller has any single store grab enabled-->
<?php if($grabSellerFlag === false){?>
<button type="submit" title="Save" id="manage-free-delivery" class="button add" value="Add Row">
    <span><span><span>Manage Free Delivery</span></span></span>
</button>
<?php } ?>

<div class="left-delivery-div">
<div id="delivery-range-main-div">
    <h4>Set distance in Kms for providing delivery service to your Customer ordering from Bakeway.</h4>
    <ul>
        <li> System will not take orders for you if destination address is outside the range specified below.</li>
        <li> Shortest distance is measured between your shop address & customer destination address</li>
        <li> Delivery Fee to be selected as per delivery range & will be taxable to the customer</li>
    </ul>
    <span class="delivery"> <h4>Turn On Delivery Service</h4></span>
    <div class="deliveryoption"><input id="delivery-yes" type="radio" name="is_delivery" value="1" <?php if ($_DeliveryValue == 1): ?> checked=checked <?php endif; ?>>Yes
        <span style="padding-right: 10px;">&nbsp;</span>
        <input id="delivery-no" type="radio" name="is_delivery" value="0" <?php if ($_DeliveryValue == 0): ?> checked=checked <?php endif; ?>>No
        <span style="padding-right: 10px;">&nbsp;</span>
        <?php if($grabSellerFlag === true) {?>
            <button type="submit" title="Save"   onclick="return alert('<?php echo __("Please contact admin for help") ?>')"  class="button add delivery" value="Add Row">
                <span><span><span>SAVE</span></span></span>
            </button>

        <?php }else {?>
            <button type="submit" title="Save" id="add-delivery" class="button add delivery" value="Add Row">
                <span><span><span>SAVE</span></span></span>
            </button>

        <?php }?>
    </div>
    </br></br>
    <div style="display: none;">
    <span class="delivery"> <h4>Enable Delivery using GRAB</h4></span>
    <div class="deliveryoption">
        <input id="grab-delivery-yes" type="radio" name="is_grab_active" value="1" <?php if ($grabValue == 1): ?> checked=checked <?php endif; ?>>Yes
        <span style="padding-right: 10px;">&nbsp;</span>
        <input id="grab-delivery-no" type="radio" name="is_grab_active" value="0" <?php if ($grabValue == 0): ?> checked=checked <?php endif; ?>>No
        <span style="padding-right: 10px;">&nbsp;</span>
        <button type="submit" title="Save" id="add-grab-delivery" class="button add grab delivery" value="Add Row">
            <span><span><span>SAVE</span></span></span>
        </button>
    </div>
    </div>
</div>
<script>
    require([
        "jquery",
        'Magento_Ui/js/modal/confirm'

    ], function($, confirmation){

        <?php if($grabSellerFlag === false)?>
        {
         $("#add-delivery").on('click',function(event){
			if (document.getElementById('delivery-yes').checked) {
                    var status = document.getElementById('delivery-yes').value;
                } else if (document.getElementById('delivery-no').checked) {
                    var status = document.getElementById('delivery-no').value;
                }

			    var seller_id = document.getElementById('seller_id').value;
                var url = event.currentTarget.href;
                if (status == 0)
                    var sta = 'off';
                else {
                    var sta = 'on';
                }

            confirmation({
                content: 'Do you wish to make delivery ' + sta + '?',
                actions: {
                    confirm: function(){
                        new Ajax.Request('<?php echo $this->getUrl('deliveryrangeprice/index/deliveryapi', ['_secure' => true]); ?>', {
                            method: 'post',
                            dataType: "json",
                            parameters:{seller_id: seller_id,
                                    status: status},
                            onSuccess: function(transport){

                            }
                        });
                    },
                    cancel: function(){}
                }
            });
        });
        }
        $("#add-grab-delivery").on('click',function(event){

            if (document.getElementById('grab-delivery-yes').checked) {
                var status = document.getElementById('grab-delivery-yes').value;
            } else if (document.getElementById('grab-delivery-no').checked) {
                var status = document.getElementById('grab-delivery-no').value;
            }
            var seller_id = document.getElementById('seller_id').value;
            new Ajax.Request('<?php echo $this->getUrl('grab/index/save', ['_secure' => true]); ?>', {
                method: 'post',
                dataType: "json",
                parameters:{seller_id: seller_id,
                    status: status},
                onSuccess: function(transport){

                    //window.location.href="<?php echo $this->getUrl('customer/index/edit/',array('id' => $block->getCustomerId(), '_current' => true,'mode' =>'delivery_price_target'))?>";

                }

            });
        });
    });


    require(['jquery', 'jquery/ui'], function ($) {
        $("#manage-delivery").click(function(){

            $(".left-delivery-div").slideDown("fast");
            $(".right-delivery-div").slideUp("fast");
            $("#manage-delivery").addClass("active-delivery-button");
            $("#manage-free-delivery").removeClass("active-delivery-button");

        });
        $("#manage-free-delivery").click(function(){

            $(".left-delivery-div").slideUp("fast");
            $(".right-delivery-div").slideDown("fast");
            $("#manage-free-delivery").addClass("active-delivery-button");
            $("#manage-delivery").removeClass("active-delivery-button");

        });


        $("#save-free-delivery").on('click',function(event){


            var seller_id = document.getElementById('current_vendorid').value;
            var max_value = document.getElementById('max-price-value').value;
            if(max_value.length !== 0) {

                new Ajax.Request('<?php echo $this->getUrl('deliveryrangeprice/freeshipping/save', ['_secure' => true]); ?>', {
                    method: 'post',
                    dataType: "json",
                    parameters: {
                        seller_id: seller_id,
                        max_value: max_value
                    },
                    onSuccess: function (transport) {

                        window.location.href = "<?php echo $this->getUrl('customer/index/edit/', array('id' => $block->getCustomerId(), '_current' => true, 'mode' => 'manage_free_delivery_save_target'))?>";

                    }

                });
            }
        });


        $(".onoffswitch-inner").click(function() {
            var seller_id = document.getElementById('current_vendorid').value;

            if ($("#freedeliveryonoffswitch").prop('checked')) {

                var free_delivery = 0; //true
            }else{
                var free_delivery = 1; //false
            }
            new Ajax.Request('<?php echo $this->getUrl('deliveryrangeprice/freeshipping/freeshippingstatus', ['_secure' => true]); ?>', {
                method: 'post',
                dataType: "json",
                parameters: {
                    seller_id: seller_id,
                    free_delivery: free_delivery
                },
                onSuccess: function (transport) {

                    window.location.href = "<?php echo $this->getUrl('customer/index/edit/', array('id' => $block->getCustomerId(), '_current' => true, 'mode' => 'manage_free_delivery_save_target'))?>";

                }

            });

        });
    });


</script>
<?php echo $block->getChildHtml('griddelivery'); ?>
</div>
<?php   $collection  = $logsHelper->getFreeShippingLogsCollection($block->getCustomerId());?>

<div class="right-delivery-div" style="display: none;">
    <br>
    <?php  if (count($collection) > 0) {?>
    <h4><?php echo __("Free Delivery :")?></h4>
    <div class="onoffswitch">
        <?php $sellerFreeDeliveryFlag = $deliveryRangepricehelper->getSellerFreeShippingFlag($block->getCustomerId()); ?>
        <input echo type="checkbox" name="freedeliveryonoffswitch" class="onoffswitch-checkbox" id="freedeliveryonoffswitch"
            <?php if($sellerFreeDeliveryFlag == 1){?>
                checked="checked"
            <?php }?>
        >
        <label class="onoffswitch-label" for="freedeliveryonoffswitch">
            <span class="onoffswitch-inner"></span>
            <span class="onoffswitch-switch"></span>
        </label>
    </div>
<?php }?>
    <form>
    <input type="hidden" value="<?php echo $block->getCustomerId()?>" id="current_vendorid" name="current_vendorid" />

        <div class="admin__field field field-commission " data-ui-id="newsletter-fieldset-element-form-field-commission">
            <label class="label admin__field-label" for="marketplace_commission" data-ui-id="newsletter-fieldset-element-text-commission-label"><span><?php echo __("Max. Input Price");?></span></label>
            <div class="admin__field-control control">
                <input id="max-price-value" name="max-price-value" required  class="input-text admin__control-text" type="text">
            </div>
        </div>

        <br>
        <div class="save-max-price">
            <button type="submit" title="Save" id="save-free-delivery" class="button add" value="Add Row">
                <span><span><span>Save</span></span></span>
            </button>
        </div>


    </form>



    <!-- logs collection start-->



    <div class="free-shipping-div">
        <?php
        if (count($collection) > 0) {?>


        <span class="free-ship-title"><strong><h5><?php echo __("Free Shipping Logs")?></h5></strong></span>

            <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
                <table class="data-grid" id="commissionid_table">
                    <thead>
                    <tr>
                        <th data-sort="commission_rate" data-direction="asc" class="data-grid-th _sortable not-sort  col-commission_rate"><span>Sr. no</span></th>

                        <th data-sort="commission_rate" data-direction="asc" class="data-grid-th _sortable not-sort  col-commission_rate"><span>Free Shipping Rate</span></th>
                        <th data-sort="created_at" data-direction="asc" class="data-grid-th _sortable not-sort  col-created_at"><span>Updated Date</span></th>
                        <th data-sort="created_by" data-direction="asc" class="data-grid-th _sortable not-sort  col-created_by"><span>Updated By</span></th>
                    </tr>

                    </thead>
                    <tbody>
                    <?php
                    $i = 1;
                    foreach ($collection as $item) { ?>

                        <tr>
                            <td  <?php if($i==1) { ?> style="color: green;font-weight: bold;  font-size: 18px;" <?php }?>"><?php echo $i; ?></td>
                            <td  <?php if($i==1) { ?> style="color: green;font-weight: bold;  font-size: 18px;" <?php }?>"><?php echo $item['max_free_shipping_price']; ?></td>
                            <td  <?php if($i==1) { ?> style="color: green;font-weight: bold;  font-size: 18px;" <?php }?>"><?php echo $item['created_at']; ?></td>
                            <td  <?php if($i==1) { ?> style="color: green;font-weight: bold;  font-size: 18px;" <?php }?>"><?php echo $item['created_by']; ?></td>
                        </tr>
                        <?php $i++;
                    } ?>
                    </tr>

                    </tbody>
                </table>

                <?php
                } else {
                    ?>
                    <div class="message info empty"><span><?php /* @escapeNotVerified */
                            echo __('No Records Found.') ?></span></div>

                <?php } ?>

            </div>



    </div>
    <!-- logs collection end-->
</div>

